version: '3.9'

services:
  db:
    image: postgres:15
    container_name: odc_postgres
    environment:
      POSTGRES_DB: odcdb
      POSTGRES_USER: odcuser
      POSTGRES_PASSWORD: odcpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: odc-backend
    image: mormbathie/odc1-backend:latest
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=odcdb
      - DB_USER=odcuser
      - DB_PASSWORD=odcpass
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: odc_frontend
    image: mormbathie/odc1-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:
  static_volume:
